### ISSUE TITLE
Error every project refresh - Unable to parse file Assets/Readme.asset

### ISSUE THREAD

**Issue by theyonatan** [JohnAlbin/UnityReadme#2]
Unable to parse file Assets/Readme.asset: [Parser Failure at line 24: Expect ':' between key and value within mapping]

UnityEngine.StackTraceUtility:ExtractStackTrace ()
FishNet.Editing.Finding:GetScriptableObjects<FishNet.Managing.Object.DefaultPrefabObjects> (bool,bool) (at Assets/SteamWorks/FishNet/Runtime/Editor/Finding.cs:202)
FishNet.Editing.DefaultPrefabsFinder:GetDefaultPrefabsFile (bool&) (at Assets/SteamWorks/FishNet/Runtime/Editor/DefaultPrefabsFinder.cs:37)
FishNet.Editing.PrefabProcessor:OnPostprocessAllAssets (string[],string[],string[],string[]) (at Assets/SteamWorks/FishNet/Runtime/Editor/PrefabProcessor.cs:29)
UnityEditor.AssetPostprocessingInternal:PostprocessAllAssets (string[],string[],string[],string[],string[],bool)

![image](https://user-images.githubusercontent.com/82711045/166100493-b5467d1f-e4b4-4c42-929c-47ae6f307ef4.png)

**Comment by theyonatan** [comment]
Apperently it was colliding with a different package,
Error unrelated to this. Sorry!

**Comment by decimate** [comment]
Just remove the colon in the "Text" at line 20 and 43.
